# Generated by Django 3.2 on 2023-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('books', models.ManyToManyField(to='main.Book')),
            ],
        ),
    ]
